export { default as AppMain } from './AppMain.vue'
export { default as Navbar } from './navigation_bar/Index.vue'
export { default as Settings } from './settings/Index.vue'
export { default as Sidebar } from './side_bar/Index.vue'
export { default as TagsView } from './tags_view/Index.vue'
